In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error,mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

In [2]:
#import dataset
train=pd.read_csv('./datasets/train.csv')
test=pd.read_csv('./datasets/test.csv')

In [3]:

train['Neighborhood'].unique()

array(['Sawyer', 'SawyerW', 'NAmes', 'Timber', 'Edwards', 'OldTown',
       'BrDale', 'CollgCr', 'Somerst', 'Mitchel', 'StoneBr', 'NridgHt',
       'Gilbert', 'Crawfor', 'IDOTRR', 'NWAmes', 'Veenker', 'MeadowV',
       'SWISU', 'NoRidge', 'ClearCr', 'Blmngtn', 'BrkSide', 'NPkVill',
       'Blueste', 'GrnHill', 'Greens', 'Landmrk'], dtype=object)

In [4]:
# Define a mapping from neighborhood names to ordinal values (you can adjust this based on your criteria)
neighborhood_mapping = {
    'Sawyer': 1,
    'SawyerW': 2,
    'NAmes': 3,
    'Timber': 4,
    'Edwards': 5,
    'OldTown': 6,
    'BrDale': 7,
    'CollgCr': 8,
    'Somerst': 9,
    'Mitchel': 10,
    'StoneBr': 11,
    'NridgHt': 12,
    'Gilbert': 13,
    'Crawfor': 14,
    'IDOTRR': 15,
    'NWAmes': 16,
    'Veenker': 17,
    'MeadowV': 18,
    'SWISU': 19,
    'NoRidge': 20,
    'ClearCr': 21,
    'Blmngtn': 22,
    'BrkSide': 23,
    'NPkVill': 24,
    'Blueste': 25,
    'GrnHill': 26,
    'Greens': 27,
    'Landmrk': 28
}

train['Neighborhood'] = train['Neighborhood'].map(neighborhood_mapping)
test['Neighborhood'] = test['Neighborhood'].map(neighborhood_mapping)
print(train[['Neighborhood']].head())


   Neighborhood
0             1
1             2
2             3
3             4
4             2


In [5]:
train['Street'].unique()

array(['Pave', 'Grvl'], dtype=object)

In [6]:

street_mapping = {
    'Pave': 1,
    'Grvl': 2
}


train['Street'] = train['Street'].map(street_mapping)
test['Street'] = test['Street'].map(street_mapping)

print(train[['Street']].head())


   Street
0       1
1       1
2       1
3       1
4       1


In [7]:
train['MS Zoning'].unique()

array(['RL', 'RM', 'FV', 'C (all)', 'A (agr)', 'RH', 'I (all)'],
      dtype=object)

In [8]:
# Define a mapping from MS Zoning values to ordinal values
ms_zoning_mapping = {
    'RL': 1,
    'RM': 2,
    'FV': 3,
    'C (all)': 4,
    'A (agr)': 5,
    'RH': 6,
    'I (all)': 7
}

train['MS Zoning'] = train['MS Zoning'].map(ms_zoning_mapping)

test['MS Zoning'] = test['MS Zoning'].map(ms_zoning_mapping)


In [9]:
train['MS Zoning'].unique()

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
train['Lot Frontage']=train['Lot Frontage'].fillna(train['Lot Frontage'].mean())
train.drop(columns=['Alley', 'Pool QC', 'Misc Feature'], inplace=True)
train.drop(columns=['Fence'], inplace=True)
train.drop(['Garage Yr Blt'],axis=1,inplace=True)
train['Bsmt Cond']=train['Bsmt Cond'].fillna(train['Bsmt Cond'].mode()[0])
train['Bsmt Qual']=train['Bsmt Qual'].fillna(train['Bsmt Qual'].mode()[0])
train['Fireplace Qu']=train['Fireplace Qu'].fillna(train['Fireplace Qu'].mode()[0])
train['Garage Type']=train['Garage Type'].fillna(train['Garage Type'].mode()[0])
train['Garage Finish']=train['Garage Finish'].fillna(train['Garage Finish'].mode()[0])
train['Garage Qual']=train['Garage Qual'].fillna(train['Garage Qual'].mode()[0])
train['Garage Cond']=train['Garage Cond'].fillna(train['Garage Cond'].mode()[0])
train['Mas Vnr Type']=train['Mas Vnr Type'].fillna(train['Mas Vnr Type'].mode()[0])
train['Mas Vnr Area']=train['Mas Vnr Area'].fillna(train['Mas Vnr Area'].mode()[0])
train['Bsmt Exposure']=train['Bsmt Exposure'].fillna(train['Bsmt Exposure'].mode()[0])
train['BsmtFin Type 2']=train['BsmtFin Type 2'].fillna(train['BsmtFin Type 2'].mode()[0])
train['Utilities']=train['Utilities'].fillna(train['Utilities'].mode()[0])
train['Exterior 1st']=train['Exterior 1st'].fillna(train['Exterior 1st'].mode()[0])
train['Exterior 2nd']=train['Exterior 2nd'].fillna(train['Exterior 2nd'].mode()[0])
train['BsmtFin Type 1']=train['BsmtFin Type 1'].fillna(train['BsmtFin Type 1'].mode()[0])
train['BsmtFin SF 1']=train['BsmtFin SF 1'].fillna(train['BsmtFin SF 1'].mean())
train['BsmtFin SF 2']=train['BsmtFin SF 2'].fillna(train['BsmtFin SF 2'].mean())
train['Bsmt Unf SF']=train['Bsmt Unf SF'].fillna(train['Bsmt Unf SF'].mean())
train['Total Bsmt SF']=train['Total Bsmt SF'].fillna(train['Total Bsmt SF'].mean())
train['Bsmt Full Bath']=train['Bsmt Full Bath'].fillna(train['Bsmt Full Bath'].mode()[0])
train['Bsmt Half Bath']=train['Bsmt Half Bath'].fillna(train['Bsmt Half Bath'].mode()[0])
train['Kitchen Qual']=train['Kitchen Qual'].fillna(train['Kitchen Qual'].mode()[0])
train['Functional']=train['Functional'].fillna(train['Functional'].mode()[0])
train['Garage Cars']=train['Garage Cars'].fillna(train['Garage Cars'].mean())
train['Garage Area']=train['Garage Area'].fillna(train['Garage Area'].mean())
train['Sale Type']=train['Sale Type'].fillna(train['Sale Type'].mode()[0])

In [11]:
## Fill Missing Values with mean for numerical features
test['Lot Frontage']=test['Lot Frontage'].fillna(test['Lot Frontage'].mean())
test.drop(columns=['Alley', 'Pool QC', 'Misc Feature'], inplace=True)
test['Bsmt Cond']=test['Bsmt Cond'].fillna(test['Bsmt Cond'].mode()[0])
test['Bsmt Qual']=test['Bsmt Qual'].fillna(test['Bsmt Qual'].mode()[0])
test['Fireplace Qu']=test['Fireplace Qu'].fillna(test['Fireplace Qu'].mode()[0])
test['Garage Type']=test['Garage Type'].fillna(test['Garage Type'].mode()[0])
test.drop(['Garage Yr Blt'],axis=1,inplace=True)
test['Garage Finish']=test['Garage Finish'].fillna(test['Garage Finish'].mode()[0])
test['Garage Qual']=test['Garage Qual'].fillna(test['Garage Qual'].mode()[0])
test['Garage Cond']=test['Garage Cond'].fillna(test['Garage Cond'].mode()[0])
test['Mas Vnr Type']=test['Mas Vnr Type'].fillna(test['Mas Vnr Type'].mode()[0])
test['Mas Vnr Area']=test['Mas Vnr Area'].fillna(test['Mas Vnr Area'].mode()[0])
test['Bsmt Exposure']=test['Bsmt Exposure'].fillna(test['Bsmt Exposure'].mode()[0])
test['BsmtFin Type 2']=test['BsmtFin Type 2'].fillna(test['BsmtFin Type 2'].mode()[0])
test['Utilities']=test['Utilities'].fillna(test['Utilities'].mode()[0])
test['Exterior 1st']=test['Exterior 1st'].fillna(test['Exterior 1st'].mode()[0])
test['Exterior 2nd']=test['Exterior 2nd'].fillna(test['Exterior 2nd'].mode()[0])
test['BsmtFin Type 1']=test['BsmtFin Type 1'].fillna(test['BsmtFin Type 1'].mode()[0])
test['BsmtFin SF 1']=test['BsmtFin SF 1'].fillna(test['BsmtFin SF 1'].mean())
test['BsmtFin SF 2']=test['BsmtFin SF 2'].fillna(test['BsmtFin SF 2'].mean())
test['Bsmt Unf SF']=test['Bsmt Unf SF'].fillna(test['Bsmt Unf SF'].mean())
test['Total Bsmt SF']=test['Total Bsmt SF'].fillna(test['Total Bsmt SF'].mean())
test['Bsmt Full Bath']=test['Bsmt Full Bath'].fillna(test['Bsmt Full Bath'].mode()[0])
test['Bsmt Half Bath']=test['Bsmt Half Bath'].fillna(test['Bsmt Half Bath'].mode()[0])
test['Kitchen Qual']=test['Kitchen Qual'].fillna(test['Kitchen Qual'].mode()[0])
test['Functional']=test['Functional'].fillna(test['Functional'].mode()[0])
test['Garage Cars']=test['Garage Cars'].fillna(test['Garage Cars'].mean())
test['Garage Area']=test['Garage Area'].fillna(test['Garage Area'].mean())
test['Sale Type']=test['Sale Type'].fillna(test['Sale Type'].mode()[0])
test.drop(columns=['Fence'], inplace=True)

In [12]:
# Define the ordinal mapping for 'Kitchen Qual'
qual_mapping = {
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1
}

# Apply the mapping to the 'Kitchen Qual' column
train['Kitchen Qual'] = train['Kitchen Qual'].map(qual_mapping)

train['Kitchen Qual'].unique()

array([4, 3, 2, 5])

In [13]:
train['Exter Qual'] = train['Exter Qual'].map(qual_mapping)

print(train['Exter Qual'].head())



0    4
1    4
2    3
3    3
4    3
Name: Exter Qual, dtype: int64


In [14]:
test['Bsmt Qual'].unique()

array(['Fa', 'Gd', 'TA', 'Ex', 'Po'], dtype=object)

In [15]:
train['Bsmt Qual']=train['Bsmt Qual'].map(qual_mapping)

test['Bsmt Qual']=test['Bsmt Qual'].map(qual_mapping)

In [16]:
qual_mapping = {
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1
}

# Apply the mapping to the 'Kitchen Qual' column
test['Kitchen Qual'] = test['Kitchen Qual'].map(qual_mapping)

test['Exter Qual'] = test['Exter Qual'].map(qual_mapping)

test['Garage Qual'] = test['Garage Qual'].map(qual_mapping)
train['Garage Qual'] = train['Garage Qual'].map(qual_mapping)

In [17]:
test['Garage Qual'].unique()

array([1, 3, 2, 4])

In [18]:

lot_shape_mapping = {
    'Reg': 4,  
    'IR1': 3,  
    'IR2': 2,  
    'IR3': 1   
}


train['Lot Shape'] = train['Lot Shape'].map(lot_shape_mapping)
test['Lot Shape'] = test['Lot Shape'].map(lot_shape_mapping)

print(train['Lot Shape'].unique())


[3 4 2 1]


In [19]:
bldg_type_mapping = {
    '1Fam': 4,      
    '2Fm': 3,       
    'Duplex': 2,    
    'TwnhsE': 1,    
    'TwnhsI': 0     
}

house_style_mapping = {
    '2Story': 7,    
    '1Story': 6,    
    '1.5Fin': 5,    
    'SFoyer': 4,    
    'SLvl': 3,      
    '2.5Unf': 2,    
    '2.5Fin': 1,    
    '1.5Unf': 0     
}

train['Bldg Type'] = train['Bldg Type'].map(bldg_type_mapping)
train['House Style'] = train['House Style'].map(house_style_mapping)

print(train[['Bldg Type', 'House Style']].head())


   Bldg Type  House Style
0        4.0            7
1        4.0            7
2        4.0            6
3        4.0            7
4        4.0            5


In [20]:
bldg_type_mapping = {
    '1Fam': 4,      
    '2Fm': 3,       
    'Duplex': 2,    
    'TwnhsE': 1,    
    'TwnhsI': 0     
}

house_style_mapping = {
    '2Story': 7,    
    '1Story': 6,    
    '1.5Fin': 5,    
    'SFoyer': 4,    
    'SLvl': 3,      
    '2.5Unf': 2,    
    '2.5Fin': 1,    
    '1.5Unf': 0     
}

test['Bldg Type'] = test['Bldg Type'].map(bldg_type_mapping)
test['House Style'] = test['House Style'].map(house_style_mapping)

print(test[['Bldg Type', 'House Style']].head())

   Bldg Type  House Style
0        NaN            7
1        2.0            6
2        4.0            7
3        4.0            6
4        4.0            6


In [21]:

lot_config_mapping = {
    'CulDSac': 4,  
    'Inside': 3,   
    'Corner': 2,   
    'FR2': 1,      
    'FR3': 0      
}


train['Lot Config'] = train['Lot Config'].map(lot_config_mapping)
test['Lot Config'] = test['Lot Config'].map(lot_config_mapping)



In [22]:
train[['Exter Qual','Gr Liv Area','Street', 'MS Zoning','Kitchen Qual','Lot Shape','Lot Config','Overall Qual','Neighborhood','House Style']].dtypes

Exter Qual      int64
Gr Liv Area     int64
Street          int64
MS Zoning       int64
Kitchen Qual    int64
Lot Shape       int64
Lot Config      int64
Overall Qual    int64
Neighborhood    int64
House Style     int64
dtype: object

In [23]:
X = train[['Exter Qual','Gr Liv Area','Street', 'MS Zoning','Kitchen Qual','Lot Shape','Lot Config','Overall Qual','Neighborhood']]
y = train['SalePrice']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [24]:
model = LinearRegression()


In [25]:
model.fit(X_train, y_train)

LinearRegression()

In [26]:
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(f'R-squared: {r2:.4f}')
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print('RMSE:', rmse)

R-squared: 0.8042
RMSE: 34107.50597730525


In [27]:
test[['Exter Qual','Gr Liv Area','Street', 'MS Zoning','Kitchen Qual','Lot Shape','Lot Config','Overall Qual','Neighborhood']].dtypes

Exter Qual      int64
Gr Liv Area     int64
Street          int64
MS Zoning       int64
Kitchen Qual    int64
Lot Shape       int64
Lot Config      int64
Overall Qual    int64
Neighborhood    int64
dtype: object

In [28]:
X = test[['Exter Qual','Gr Liv Area','Street', 'MS Zoning','Kitchen Qual','Lot Shape','Lot Config','Overall Qual','Neighborhood']]






In [29]:
preds=model.predict(test[['Exter Qual','Gr Liv Area','Street', 'MS Zoning','Kitchen Qual','Lot Shape','Lot Config','Overall Qual','Neighborhood']])

In [30]:
#save predictions
#save predictions
submission18=pd.DataFrame({'Id':test['Id']})
submission18['SalePrice'] = preds
submission18.head()

Id      SalePrice
0  2658  155947.511733
1  2718  168725.996184
2  2414  230516.936890
3  1989  130472.729134
4   625  159183.212056

In [31]:
submission18.to_csv('datasets/kaggle_submission_18.csv', index=False)

In [32]:
X = train[['Lot Area','Gr Liv Area','Overall Qual','Total Bsmt SF','Garage Cars','Bsmt Qual','Garage Qual','Lot Config','Overall Cond']]
y = train['SalePrice']

In [33]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [35]:
train['Overall Cond'].unique()

array([8, 5, 7, 6, 3, 9, 2, 4, 1])

In [36]:
test[['Lot Area','Gr Liv Area','Overall Qual','Total Bsmt SF','Garage Cars','Bsmt Qual','Garage Qual','Lot Config','Overall Cond']].isna().sum()
test['Kitchen Qual'].fillna(0, inplace=True)

In [37]:
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(f'R-squared: {r2:.4f}')
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print('RMSE:', rmse)

R-squared: 0.8444
RMSE: 30409.748727362963


In [38]:
preds=model.predict(test[['Lot Area','Gr Liv Area','Overall Qual','Total Bsmt SF','Garage Cars','Bsmt Qual','Garage Qual','Lot Config','Overall Cond']])

In [39]:
submission23=pd.DataFrame({'Id':test['Id']})
submission23['SalePrice'] = preds
submission23.head()

Id      SalePrice
0  2658  136683.468031
1  2718  208943.389689
2  2414  208828.871666
3  1989  116151.306900
4   625  194692.236509

In [40]:
submission23.to_csv('datasets/kaggle_submission_23.csv', index=False)

In [41]:
#Model-iterate
from sklearn.linear_model import Ridge
X = train[['Lot Area','Gr Liv Area','Overall Qual','Total Bsmt SF','Garage Cars','Bsmt Qual','Garage Qual','Lot Config','Overall Cond']]
y = train['SalePrice']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [51]:
#source google
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train linear regression model
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Print the coefficients and intercept
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Mean Squared Error: 924752817.6613595
Coefficients: [ 6580.82461294 20805.6750283  26994.70718043 10997.27868597
 10633.69973896 16585.03531754  2806.97640968  2992.57198607
  4952.59316632]
Intercept: 181718.5274390244


In [55]:


# Create the plot
plt.figure(figsize=(8, 6))  # Adjust figure size if needed
plt.plot(x, y, label=f'y = {model.coef:.2f}x + {model.intercept_:.2f}')

# Add labels and title
plt.xlabel('x')
plt.ylabel('y')
plt.title('Graph of Linear Equation')

# Add grid for better readability
plt.grid(True)

# Add legend
plt.legend()

# Show the plot
plt.show()

NameError: name 'x' is not defined

<Figure size 800x600 with 0 Axes>

In [47]:
#source Google
alpha = 1.0
ridge_model = Ridge(alpha=alpha)

# Fit the model to the training data
ridge_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = ridge_model.predict(X_test)

# Evaluate the model (e.g., using mean squared error)
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Print the coefficients of the model
print(f"Coefficients: {ridge_model.coef_}")
print(f"Intercept: {ridge_model.intercept_}")

Mean Squared Error: 924569628.3282114
Coefficients: [1.18093895e+00 4.11649935e+01 1.89573100e+04 2.43291253e+01
 1.38650825e+04 2.37777829e+04 1.11263428e+04 5.05192224e+03
 4.49454159e+03]
Intercept: -215434.71942610797
